### ISSUE TITLE
Duo2 boot problem

### ISSUE THREAD

**Issue by Dima73** [oe-alliance/openmultibootmanager#14]
box vu+duo2 ,use openmultiboot
flash image - openATV
usb openmultiboot:
1)openPLi 4.0
2)VTI

boot openPLi --> image running ok
set nex boot VTI --> not loading box -->stuck on the splash screen
turn off power and turn on power -->boot VTI--> image running ok

Please, please help !!!

log with COM  port(it's not my log):
[multiboot_atv.zip](https://github.com/oe-alliance/openmultibootmanager/files/456650/multiboot_atv.zip)

**Comment by arn354** [comment]
There was an UBI error 
and several
Traceback (most recent call last):
  File "/sbin/open-multiboot-branding-helper.py", line 61, in <module>
    import boxbranding
ImportError: No module named boxbranding
Traceback (most recent call last):
  File "/sbin/open-multiboot-branding-helper.py", line 61, in <module>
    import boxbranding
ImportError: No module named boxbranding


CPU 0 Unable to handle kernel paging request at virtual address 00000000, epc == e0d6eac8, ra == e0d6bbf0
Oops[#1]:
CPU: 0 PID: 415 Comm: Nexus_Image Tainted: P           O 3.13.5 #1
task: cf6404a0 ti: ce37e000 task.ti: ce37e000
$ 0   : 00000000 30008700 e0d6eac0 ce3b8084
$ 4   : 00000000 00000000 00000000 00000065
$ 8   : 00000000 0040e040 800f5410 00000000
$12   : 76ee8e48 7757d380 00000000 00000000
$16   : 00000000 ce3dfb00 76ee8e40 00650005
$20   : ce3dfb00 00000000 cf431000 00000000
$24   : 00000000 e0ec90e4                  
$28   : ce37e000 ce37fdf8 76ee8ec8 e0d6bbf0
Hi    : 00000096
Lo    : 00001dea
epc   : e0d6eac8 NEXUS_Module_Lock_Tagged+0x8/0x10 [dvb_base]
    Tainted: P           O
ra    : e0d6bbf0 nexus_driver_platform_ioctl+0xf8/0x2a18 [dvb_base]
Status: 30008703	KERNEL EXL IE 
Cause : 80800008
BadVA : 00000000
PrId  : 00025a11 (Broadcom BMIPS5000)
Modules linked in: dvb_base(PO) bcm_event(PO) procmk(O) rt5370sta(O) rt2x00usb rt2x00lib mac80211 libcrc32c
Process Nexus_Image (pid: 415, threadinfo=ce37e000, task=cf6404a0, tls=76ef0930)
Stack : ce3a7c80 800c46a4 ce3b8084 8006c3e0 00000010 00000003 82012300 82012338
	  ce3b8084 e1063364 ce3dfb00 00650005 e1132930 e10e0000 00000000 766ea000
	  00000000 e0d6957c 80703cc0 820126f0 00000001 8007e4b8 00000000 8003a718
	  76ee8e40 00000001 00000000 76ee8e40 cf422900 cde3dd48 00650005 00000005
	  00000005 e0d678e0 00000009 00000024 806f00a4 806f0080 806fe3e4 800f5224
	  ...
Call Trace:
[<e0d6eac8>] NEXUS_Module_Lock_Tagged+0x8/0x10 [dvb_base]
[<e0d6bbf0>] nexus_driver_platform_ioctl+0xf8/0x2a18 [dvb_base]
[<e0d6957c>] nexus_generic_driver_ioctl+0xe0/0x20c [dvb_base]
[<e0d678e0>] nexus_driver_ioctl+0x4c/0x7c [dvb_base]
[<800f5224>] do_vfs_ioctl+0x42c/0x618
[<800f5460>] SyS_ioctl+0x50/0x90
[<80011154>] handle_sys+0x134/0x158


Code: 24020001  3c19e0ed  273990e4 <03200008> 8c840000  27bdffd8  afb00014  3c10e114  afb10018 
---[ end trace c2a58f20fd46dcb6 ]---
CPU 1 Unable to handle kernel paging request at virtual address 00000000, epc == e0d6eac8, ra == e0d6bbf0
Oops[#2]:
CPU: 1 PID: 411 Comm: dvb_server Tainted: P      D    O 3.13.5 #1
task: cfe744a0 ti: ce3dc000 task.ti: ce3dc000
$ 0   : 00000000 10008b00 e0d6eac0 ce3b8084
$ 4   : 00000000 00000000 00000000 00000065
$ 8   : 00000000 0040e100 800f5410 00000100
$12   : 7fadfa40 7757d380 771e8794 00000000
$16   : 00000000 ce3dfb00 7fadfa38 00650005
$20   : ce3dfb00 00000000 cf431000 00000000
$24   : 00000000 e0ec90e4                  
$28   : ce3dc000 ce3dddf8 7fadfae0 e0d6bbf0
Hi    : 000000e8
Lo    : 00d6e1ed
epc   : e0d6eac8 NEXUS_Module_Lock_Tagged+0x8/0x10 [dvb_base]
    Tainted: P      D    O
ra    : e0d6bbf0 nexus_driver_platform_ioctl+0xf8/0x2a18 [dvb_base]
Status: 10008b03	KERNEL EXL IE 
Cause : 80800008
BadVA : 00000000
PrId  : 00025a11 (Broadcom BMIPS5000)
Modules linked in: dvb_base(PO) bcm_event(PO) procmk(O) rt5370sta(O) rt2x00usb rt2x00lib mac80211 libcrc32c
Process dvb_server (pid: 411, threadinfo=ce3dc000, task=cfe744a0, tls=775aa490)
Stack : 00000000 cfe744a0 ce3b8084 8006c3e0 00000d90 800a3990 00000005 00000000
	  ce3b8084 e1063364 ce3dfb00 00650005 e1132930 e10e0000 00000000 004b0000
	  00000000 e0d6957c 00000001 80061c04 806fddc0 8030b580 00000000 80703184
	  7fadfa38 82013500 8076f500 7fadfa38 cf422900 cde3dd48 00650005 00000005
	  00000008 e0d678e0 00000226 00000000 cf6404a0 00000000 cf6404a0 800f5224
	  ...
Call Trace:
[<e0d6eac8>] NEXUS_Module_Lock_Tagged+0x8/0x10 [dvb_base]
[<e0d6bbf0>] nexus_driver_platform_ioctl+0xf8/0x2a18 [dvb_base]
[<e0d6957c>] nexus_generic_driver_ioctl+0xe0/0x20c [dvb_base]
[<e0d678e0>] nexus_driver_ioctl+0x4c/0x7c [dvb_base]
[<800f5224>] do_vfs_ioctl+0x42c/0x618
[<800f5460>] SyS_ioctl+0x50/0x90
[<80011154>] handle_sys+0x134/0x158


Code: 24020001  3c19e0ed  273990e4 <03200008> 8c840000  27bdffd8  afb00014  3c10e114  afb10018 
---[ end trace c2a58f20fd46dcb7 ]---
/etc/rcS.d/S65vuplus-platform-util: line 3:   411 Segmentation fault      start-stop-daemon --start --quiet --exec /usr/bin/dvb_server --

It is hard to read the different logs.

another thing i remember is the volatile-media change - https://github.com/oe-alliance/oe-alliance-core/commit/8f76546210ff3ae8fa35349f492017dad61f0a62

**Comment by Dima73** [comment]
Maybe this will help?
https://github.com/oe-alliance/openmultibootmanager/pull/15
https://github.com/oe-alliance/openmultiboot/pull/19

**Comment by Dima73** [comment]
ok
As I was informed, after the duo2 tests, the problem is solved.
Thanks for the help.
