### ISSUE TITLE
Crash in Vu+Duo2 Openmultiboot

### ISSUE THREAD

**Issue by halll9000** [oe-alliance/openmultibootmanager#25]
Hi 
 
I have the same problem.
I have about 6 image in multiboot but only Openpli chash
 
Can you help me?
 
Thanks
 

[crash.zip](https://github.com/oe-alliance/openmultibootmanager/files/1010923/crash.zip)

**Comment by Dima73** [comment]
need add
	def isCompatible(self, base_path):
+		running_box_type = "none"

**Comment by AbuBaniaz** [comment]
Is this the same issue as here
https://github.com/oe-alliance/openmultibootmanager/issues/24
