### ISSUE TITLE
crash 19.05 after upload new plugin openmultiboot

### ISSUE THREAD

**Issue by halll9000** [oe-alliance/openmultibootmanager#26]
![crash 19_05](https://cloud.githubusercontent.com/assets/28782568/26252490/9e437686-3cb0-11e7-80df-86ad94207eec.JPG)

**Comment by arn354** [comment]
read the message. you try to update openmultiboot on a "child" image. You do not run the main image in flash to update openmultiboot. The plugin should not be installed in a child image at all - hence not being updated at all in a child image.
