### ISSUE TITLE
fix func isCompatible

### ISSUE THREAD

**Issue by Dima73** [oe-alliance/openmultibootmanager#30]
https://github.com/oe-alliance/openmultibootmanager/blob/master/src/OMBManagerList.py#L221
formuler3ip != formuler3
> root@formuler4turbo:~# cat /proc/stb/info/boxtype
formuler3
root@formuler4turbo:~# cat /etc/opkg/arch.conf
arch all 1
arch any 6
arch noarch 11
arch mips32el 16
arch formuler3ip 21
arch 3rdparty 26
arch formuler3ip_3rdparty 31
arch private 36
arch ocram 41
arch mipsel 46

**Comment by atvcaptain** [comment]
?? box formuler4turbo dont show formuler3 with  cat /proc/stb/info/boxtype  what you mean ??

**Comment by Dima73** [comment]
https://github.com/oe-alliance/openmultibootmanager/blob/master/src/OMBManagerList.py#L221
The names do not match.

**Comment by arn354** [comment]
Quote: 
root@formuler4turbo:# cat /proc/stb/info/boxtype
formuler3

current check in /etc/opkg/arch.conf looks for formuler3 but in arch.conf only formuler3ip is listed. running_box_type == box_type will not be TRUE in the current code.

Is oe-a arch.conf the same?

**Comment by Dima73** [comment]
![2018-02-02_074356 png_thumb](https://user-images.githubusercontent.com/1756274/35730833-37cf61ca-081c-11e8-9e24-9e822ac87212.jpg)

**Comment by Marchella1983** [comment]
on **formuler4turbo** there are no problems, openmultiboot works correctly...

and here on **formuler? iptv improved** works not correctly, images is loaded into the open-multiboot folder but not displayed in openmultibootmanager

**Comment by arn354** [comment]
Sure it works with oe-a images - as we use boxbranding.so there and the arch-check is not run at all.
the arch-check will only be used if the image has no boxbranding.so available.

i don't think that the simple assumption if the string from boxtype is contained in arch.conf is really sufficient. Are you sure this does not create issues for other boxes?

**Comment by Dima73** [comment]
I do not know how to make a corrected code.
I was asked to report a problem.

And by the way there is a second problem.
The new image will not load, stopping at bootlogo.
If load backup of the same image, all ok.

**Comment by arn354** [comment]
unfortunatly i have none of those boxes.
i think we should add a "elif" with this further check, so that the new check gets additionally checked as "last" option if the first one is not true. At least it will then only break something for those boxes and not the ones which have a 1:1 match.

**Comment by Marchella1983** [comment]
here look at the screens made on Formuler formuler3 iptv improved, there it is accurately visible that the unpacked image isn't displayed in openmultibootmanager

https://mega.nz/#!RF8USBjR!HoGBozEVukkAis6H_VJw6BsCAFXxfN-aEB6s_YleLp4
https://mega.nz/#!lI1hlKpT!71B-Zwx0a9MYuDNniNIct7qgV4bmcNeFQp949O4msvA
https://mega.nz/#!1d9UmQqS!pL1fxpVSvXbfEdG85FwRm3zjmF4jd75z7diR2fJyT8c
https://mega.nz/#!5Y8zyCyD!R1IFjwNcgxAdsMp6OAMcPRP5a8RQ4gaINeTN0aXGtKI

**Comment by arn354** [comment]
[OMBManagerList.zip](https://github.com/oe-alliance/openmultibootmanager/files/1704625/OMBManagerList.zip)

try this one - someone should change and debug it who has those boxes...
btw - which image are you running on formuler3 ip?

**Comment by Marchella1983** [comment]
**arn354** perfectly, everything works
https://mega.nz/#!5dMSiCLQ!InBk4FaZCPeug2hIIq4ofCsafgtxd8kamg8z605SenU
https://mega.nz/#!1d02DYII!wWhSzcoSqdX7WmN2wJDExwI7GIuYOoCMJ-XTVV1sjvE

**Comment by Dima73** [comment]
root@et1x000:~# cat /proc/stb/info/boxtype 
et11000                                     
root@et1x000:~# cat /etc/opkg/arch.conf     
arch all 1                                 
arch any 6                                 
arch noarch 11                             
arch armv5hf-vfp 16                         
arch armv5ehf-vfp 21                       
arch armv6hf-vfp 26                         
arch armv7ahf-vfp 31                       
arch armv7ahf-neon 36                       
arch et1x000 41                             
root@et1x000:~# 

``

**Comment by arn354** [comment]
grrrrr - so now it gets more complicated :D
