### ISSUE TITLE
to correct openmultiboot for Tiviar Alfa

### ISSUE THREAD

**Issue by Marchella1983** [oe-alliance/openmultibootmanager#33]
the request to correct openmultiboot for Tiviar Alfa...
![1_0_1_7_1a_1_eeee0000_0_0_0_20180503092922](https://user-images.githubusercontent.com/28537448/39560084-7dc91da4-4eb4-11e8-8f00-070530b40957.jpg)

![1_0_1_7_1a_1_eeee0000_0_0_0_20180503092840](https://user-images.githubusercontent.com/28537448/39560071-6708fd1e-4eb4-11e8-8086-797abb78f380.jpg)

**Comment by atvcaptain** [comment]
tiviamin not alfa check correct image

**Comment by Marchella1983** [comment]
oh excuse for my not attentiveness...
