### ISSUE TITLE
finnish language file (OpenMultiboot.mo) is not created

### ISSUE THREAD

**Issue by Orlandoxx** [oe-alliance/openmultibootmanager#73]
locale/fi/LC_MESSAGES/OpenMultiboot.mo is no created when installin openmultiboot plugin.

Should **fi** be added here ? : 
updateallpo.sh : LANGS = bg de el fr it lt nl pl pt ru tr

**Comment by Huevos** [comment]
There is no "fi" translation in the current branch.

https://github.com/oe-alliance/openmultibootmanager/tree/dev-bootmenu-helper/po

**Comment by Orlandoxx** [comment]
Okay, how I can put it in the 'dev-bootmenu-helper/po' ? Is it also missing from Makefile.am (LANGS = ar bg de el et fr it lt nl pl pt ru tr ) ?

**Comment by Orlandoxx** [comment]
[fi.zip](https://github.com/oe-alliance/openmultibootmanager/files/10098270/fi.zip)
 
Attached if someone can do it ?

**Comment by AbuBaniaz** [comment]
@Huevos added this. Previous commits were to master branch.

We will be using the `main` branch now, it was forked from the de-boot-menu-helper branch which will be deleted in a few days. The bitbake files on branches 4.4 onwards have been updated to reflect the branch name change.
